<?php

declare(strict_types=1);

namespace Pattern\Solid\Devuz\Liskov\Good;

class Parrot extends FlyBird
{
    public function fly()
    {
        parent::fly(); // TODO: Change the autogenerated stub
    }
}